- matplotlib2tikz.py
Like it was the code expected the colors to be single values/strings and failed for rgb tuples.  Commit f59ed39 should fix it.
> Support for marker_edge_color/marker_face_color that is not a string, but a rgb-tuple 

- matplotlib2tikz/line2d.py
- matplotlib2tikz/path.py
- matplotlib2tikz/save.py
- test/testfunctions/__init__.py
- test/testfunctions/errorbar.py
Added support for LineCollection objects used by `errorbar`. (Perhaps for `pcolormesh` and `contour` also; not tested). The LineCollection part based on pullrequest #41 by Caasar:
> The extension for the LineCollection is straight forward and used the existing _draw_path method. The _draw_path was extended with the simplify value. The default behaviour does not change, however when exporting a Line for the LineCollection it was observed that the simplification of the vertices removed to many samples for a smooth line.
(Caasar's `QuadMesh` is *not* included)
Additionally I fixed two minor bugs:
* fix horizontal line marker. Underscore is at least in my version of pgfplot (TeXLive 2013) no marker. Changed to hyphen
* avoid `AttributeError` by checking if function `lower()` in …
> Add support for LineCollection objects and two minor bugfixes

- matplotlib2tikz/text.py
The text alignment setting for text with linebreaks (e.g. in annotations) was not set correctly.
An simple example would be:
ax.annotate('line1\n line2', xy=(1, 2), horizontalalignment='right')
The default horizontal alignment is 'left'.
> Fix text alignment (e.g. in annotations)

- matplotlib2tikz/line2d.py
- test/testfunctions/legends2.py
- test/testfunctions/marker.py
Set the line style of marker edges always to 'solid'. Otherwise the line style of the actual lines os used, which in case of e.g. dotted lines leads to a wrong output.
This is also consistent with the way matplotlib set the line style of the marker edges.
A test is included.
> Fix line style of marker edges 

- matplotlib2tikz/quadmesh.py
- matplotlib2tikz/save.py
- test/testfunctions/__init__.py
- test/testfunctions/quadmesh.py
Add support for 'mpl.collections.QuadMesh', which are generated e.g. by 'plt.pcolormesh'.
The implementation relies on rendering the object using the AGG backend and save the image as png file.
A test for this (quadmesh.py) is included.
I believe this should also allow to close https://github.com/nschloe/matplotlib2tikz/pull/41, which seemed to implemented the same functionality in a similar way, however the code in https://github.com/nschloe/matplotlib2tikz/pull/41 is outdated and nonfunctional.
> Add quadmesh support

- matplotlib2tikz/line2d.py
When using [Matplotlib's boxplot](http://matplotlib.org/examples/pylab_examples/boxplot_demo.html) I get: 
```
File "/usr/local/lib/python3.4/dist-packages/matplotlib2tikz/save.py", line 146, in save
data, content = _recurse(data, figure)
File "/usr/local/lib/python3.4/dist-packages/matplotlib2tikz/save.py", line 226, in _recurse
data, children_content = _recurse(data, child)
File "/usr/local/lib/python3.4/dist-packages/matplotlib2tikz/save.py", line 235, in _recurse
data, cont = line2d.draw_line2d(data, child)
File "/usr/local/lib/python3.4/dist-packages/matplotlib2tikz/line2d.py", line 30, in draw_line2d
show_line, linestyle = _mpl_linestyle2pgfp_linestyle(obj.get_linestyle())
File "/usr/local/lib/python3.4/dist-packages/matplotlib2tikz/line2d.py", line 299, in …
```
> Fix error when using boxplot

- matplotlib2tikz/save.py
The hint to add \usepackage{fontspec} to the LaTeX code is only recommented for XeLaTeX and LuaLaTeX
> fontspec is XeLaTeX and LuaLaTeX specific

- matplotlib2tikz/image.py
When a plot with an image is saved, a file called "img1.png" is saved.
My suggestion ist, to save it as data['base name']'1.png', so the corresponding tikz file can be easily located.
> Suggestion: replace image filename

- matplotlib2tikz/image.py
The tex_relative_path_to_data was ignored while saving images.
The property origin of an image was ignored.
I'm not sure how to consider the origin flag in the else path, where PIL.Image.fromarray(...).save(...) is used.
I hope that this PR work also for Python2.
> Bugfix for image: origin was ignored

- matplotlib2tikz/patch.py
- matplotlib2tikz/save.py
- test/test_hashes.py
- test/testfunctions/__init__.py
- test/testfunctions/barchart.py
- test/testfunctions/barchart_legend.py
Hello again.  This PR is a bit more complicated and may have to be modified before you are likely to accept it.
I was looking to add the ability to render bar charts.   Even with draw_rectangles turned on, I had Latex errors, and even if that worked, the legend would not be drawn appropriately.
There are two major changes here:
1. Rectangles with a label are draw (ignoring draw_rectangles). It seems to me, rectangles with labels (although they are typically set to '_nolegend_' ) are associated with a plot and should be drawn.
2. Since bar charts have no \addplot associated, a legend must be added manually with \addlegendimage 
From page 249 of the PGFPlots manual: 
> Use \addlegendimage to provide custom styles into legends, for example to document custom \draw
commands inside of an axis. …
> Add ability to render bar charts and legends for bar charts

- matplotlib2tikz/save.py
- test/testfunctions/__init__.py
- test/testfunctions/barchart_errorbars.py
- test/testfunctions/fancybox.py
Change to respect the z-orders of objects.  The basic idea was instead of just storing the content to be written out to file in an array, maintain it in a dictionary that maps z-order to an array of content for that z-order.  Then flatten it into a single content array using the z-order.  This flattening does occur a couple times (for example all axes objects must be flattened so they can be book ended by `\begin{axis}` and `\end{axis}` correctly.
Before, bar charts with error bars were plotted as:
Now:
(The ugliness of these plots are to make sure there is a difference in the hashes, thin error bars weren't working)
> Respect Z-Orders

- matplotlib2tikz/axes.py
- test/testfunctions/__init__.py
- test/testfunctions/legends2.py
- test/testfunctions/sharex_and_y.py
Hi,
Just a small improvement related to the visibiliy of tick labels. 
For instance, when you draw subplots which share the same x and y axis, the ticklabels only appear at the bottom of the subplots' grid and at the left. With the code of the master branch, they are always plotted regardless their visibility parameter.
Regards.
> Take into account the visibility of ticklabels

- matplotlib2tikz/axes.py
- test/test_rotated_labels.py
- test/testfunctions/__init__.py
- test/testfunctions/annotate.py
- test/testfunctions/barchart.py
- test/testfunctions/barchart_errorbars.py
- test/testfunctions/barchart_legend.py
- test/testfunctions/basic_sin.py
- test/testfunctions/boxplot.py
- test/testfunctions/dual_axis.py
- test/testfunctions/errorband.py
- test/testfunctions/errorbar.py
- test/testfunctions/fillstyle.py
- test/testfunctions/legends.py
- test/testfunctions/legends2.py
- test/testfunctions/line_collection.py
- test/testfunctions/loglogplot.py
- test/testfunctions/logplot.py
- test/testfunctions/noise.py
- test/testfunctions/quadmesh.py
- test/testfunctions/rotated_labels.py
- test/testfunctions/scatter.py
- test/testfunctions/scatter_colormap.py
- test/testfunctions/sharex_and_y.py
- test/testfunctions/subplot4x4.py
- test/testfunctions/subplots.py
- test/testfunctions/subplots_with_colorbars.py
- test/testfunctions/text_overlay.py
- test/testfunctions/tick_positions.py
This patch allows arbitrary rotation of tick labels. If the rotation is the same for every label on the given axes, it will apply a global `xticklabel style`. If the rotation values differs, it will create an array of the rotation value and apply the one at the given tick index.
In addition, I've attached a small test set with different rotated labels on both, the x and y axes.
> Allow rotation of axes tick labels

- matplotlib2tikz/axes.py
By formatting the code to conform to PEP8, I forgot a backslash
causing a misbehavior. This patch fixes that, as otherwise the whole
dictionary would have been set to the variable instead of only
one value it contains.
> Fix tick label text width caused by formatting

- matplotlib2tikz/color.py
A simple fix that in `color.py` where `mpl_color2xcolor` returns `none` when the alpha value is exactly zero.
> Return 'none' when alpha value is 0

- matplotlib2tikz/axes.py
If an axes has a minor grid this grid is not displayed in tex, because the matplotlib axes object's property for the major grid is also true. Therefore the minorgrid property will never be added.
> Fix ignored minor grid if major grid is true in axes object

- matplotlib2tikz/legend.py
When using matplotlib colours like "darkorange" or "darkred"
https://github.com/nschloe/matplotlib2tikz/blob/66da89dcd5c6b3eff14602ae28e14bc10075ff00/matplotlib2tikz/legend.py#L206
creates nested RGBA codes like
```
[[ 0.54509804  0.          0.          1.        ]]
[[ 1.          0.54901961  0.          1.        ]]
```
and matplotlib will throw an error.
With this PR, the error gets caught and the function call repeated with a `numpy.squeeze` applied to the colour.
> catching error during messy RGBA colour handling

- matplotlib2tikz/files.py
- matplotlib2tikz/image.py
- matplotlib2tikz/line2d.py
- matplotlib2tikz/quadmesh.py
- matplotlib2tikz/save.py
- test/helpers.py
- test/test_externalize_tables.py
The externalized data is saved in .tsv files (uses built-in support of pgfplots).
This makes it easier to edit the style of the plot since the generated
LaTeX is smaller.
This is a feature I often use and I thought it might be worth it to upstream it.
> Add option to externalize tabular data

- matplotlib2tikz/files.py
- matplotlib2tikz/save.py
- test/test_externalize_tables.py
This is useful when running multiple times the same script, it avoids
adding indefinitely new files.
Mainly (but not only) useful as a follow-up to #232
> Add option to overwrite existing external files

- matplotlib2tikz/axes.py
- matplotlib2tikz/save.py
- test/test_deterministic_output.py
Order of parameters of tikz axis changed between calls, which caused
unnecessary diff churn when using VCS.
This makes the order deterministic.
> Make output deterministic

- matplotlib2tikz/line2d.py
- matplotlib2tikz/path.py
The current format of inline tables (using \n as a row separator) breaks in certain latex usage scenarios. This PR changes the format to use \\ to separate rows.
> use \\ row separator for more stable inline tables

- matplotlib2tikz/line2d.py
Add marker "asterisk" and "star" to list of markers (in line2d.py), which do not take an optional * for a filled version in pgfplots. With * they are not being shown in pgfplots.
This change solves this issue: nschloe#151.
> Allow "asterisk" and "star" marker to be shown when marker_face_color is set

- matplotlib2tikz/axes.py
This uses the already tested function in the matplotlib library to change the `\mathdefault{}` function that is put into the labels while plotting in `\displaystyle` and using the latex inline math environment `\(\)`.
> Fix mathdefault input into tex file

- tikzplotlib/axes.py
Double braces are required for .format to yield a single pair of braces in the output text (which we want here).
> added missing braces for .format()

- setup.py
Remove the codecs module and replace the obsolete `codecs.open` function by `open` in
Python 3.x
> Get rid of codecs module

- tikzplotlib/_axes.py
This handles plots created with `axs = f.subplots(1, 3, sharex=True, sharey=True)`
> Output ticks even if they have no labels

- test/refresh_reference_files.py
- test/test_annotate.py
- test/test_annotate_reference.tex
- test/test_arrows_reference.tex
- test/test_fancybox_reference.tex
- test/test_subplots_reference.tex
- test/test_text_overlay_reference.tex
- tikzplotlib/_text.py
This modifies `_annotation` to return the location at which the text should be rendered, and then adds support for `offset points` and `offset pixels`.
This should make it easier to add support for the other coordinate type too, but I'll leave that for someone who needs them.
> Support annotation.textcoords == "offset points"

- test/test_legend_best_location_reference.tex
- test/test_legends2_reference.tex
- test/test_sharex_and_y_reference.tex
- tikzplotlib/_axes.py
Note lack of labels on the non-edge axes of this plot with shared axes, which matches the matplotlib behavior:
> Ensure absent labels remain absent

- tikzplotlib/_axes.py
- tikzplotlib/_save.py
The motivation here was to allow
```
extra_groupstyle_parameters={f'horizontal sep={sep}'}
```
As part of something like the following to produce plots that fill the full page width:
```python
sep = r"\linewidth/24"
n = len(axs)
tikzplotlib.save("plot.tikz",
fig,
figurewidth=fR'\linewidth/{n} - {n-1}/{n}*{sep}',
figureheight=fR'\linewidth/{n} - {n-1}/{n}*{sep}',
extra_tikzpicture_parameters={'trim axis group left', 'trim axis group right'},
extra_axis_parameters={'scale only axis'},
extra_groupstyle_parameters={f'horizontal sep={sep}'})
```
An alternative would be to add new arguments specifically for this spacing.
> Add support for extra groupstyle options

- test/test_cleanfigure.py
- test/test_rotated_labels.py
- tikzplotlib/_text.py
- tikzplotlib/_util.py
The opacity of text annotation boxes is currently ignored. This small addition should take them into account.
It is related to nschloe#198, which resulted in a fix for legends, but not plain text annotations.
> Support for opacity of text annotations

- tikzplotlib/_hatches.py
this fixes #405 by presenting a warning to the user that an unknown hatch identifier was set by the user
> correctly show warning if unknown hatch identifier was used

- tikzplotlib/_path.py
`rotate=X` marker options should be placed defined as `mark options={rotate=X}`
fixes #441
> add missing "mark options={}" for scatter plots

- test/test_cleanfigure.py
- tikzplotlib/_line2d.py
In [matplotlib](https://matplotlib.org/stable/gallery/lines_bars_and_markers/masked_demo.html), nan values are just ignored, leading to interrupted plots, similar to masked values; by default [pgfplots](http://mirrors.ctan.org/graphics/pgf/contrib/pgfplots/doc/pgfplots.pdf#page=120) however discards them – drawing a line between them, having exactly the opposite behavior.
This PR changes the behavior to match matplotlib's.
I've seen that in `clean_figure()`, NaNs are used; is their usage there based upon the former assumption? In one of the tests which showed different linecount (`test_plot3d()`), I could however not spot any visual difference for the altered variant.
> Change behavior for NaN to match matplotlib

- src/tikzplotlib/_path.py
- tests/test_legend_line_scatter_reference.tex
- tests/test_marker_reference.tex
- tests/test_scatter_reference.tex
First, thank you for writing and maintaining this marvelous package!
This PR fixes #475 and fixes #479 . It only adds the `scatter` option if there was a colormap specified.
> Change to only add  option if there is cmap

- src/tikzplotlib/_cleanfigure.py
added more helpful error message when clean_figure fails due to data outside of plot
This may save people some time.
minimal example to raise the error:
```python
import numpy as np
import matplotlib.pyplot as plt
y = np.concatenate([2* np.arange(0,5), np.arange(10,20)])
x = np.arange(len(y))*3
#print(x,y)
plt.plot(x,y)
plt.ylim(5,10)
from src import tikzplotlib
tikzplotlib.clean_figure()
src = tikzplotlib.get_tikz_code()
print(src)
```
> added more helpful error message when clean_figure fails
