- .travis.yml
- README.md
- matplotlib2tikz.py
- test/testfunctions/__init__.py
- test/testfunctions/basic_sin.py
- test/testfunctions/circle_patch.py
- test/testfunctions/heat.py
- test/testfunctions/image_plot.py
- test/testfunctions/legends.py
- test/testfunctions/legends2.py
- test/testfunctions/loglogplot.py
- test/testfunctions/logplot.py
- test/testfunctions/noise.py
- test/testfunctions/noise2.py
- test/testfunctions/patches.py
- test/testfunctions/scatter.py
- test/testfunctions/subplot4x4.py
- test/testfunctions/subplots.py
- test/testfunctions/text_overlay.py
Wait for https://github.com/travis-ci/travis-ci/issues/5006 to get green light for the tests.
> Ticks direction

- matplotlib2tikz/legend.py
- test/testfunctions/legends.py
I wrote some lines for supporting the proper alignment in the legend box (Since the default value is centered...). And a bit for coloured boxes
> support for text alignment in legend box; + support for colored legend box (face and edge)

- matplotlib2tikz/save.py
- test/testfunctions/__init__.py
- test/testfunctions/errorband.py
Add support for 'mpl.collections.PolyCollection', which are generated e.g. by 'plt.fill_between'.
'mpl.collections.PolyCollection' are handled the same way as 'mpl.collections.PatchCollection'
Includes a test for this: 'errorband.py'
> Add support for 'mpl.collections.PolyCollection'

- matplotlib2tikz/line2d.py
- test/testfunctions/__init__.py
- test/testfunctions/marker.py
Fix issue https://github.com/nschloe/matplotlib2tikz/issues/94
The recently added test 'marker.py' should cover this feature too.
> line2d.py - Handel 'markevery' correctly

- matplotlib2tikz/legend.py
Use location "upper right"/1 instead as a temporary fix.
> Assertion error if legend location "best"/0 is used

- README.md
- matplotlib2tikz/__init__.py
- matplotlib2tikz/axes.py
- test/testfunctions/__init__.py
- test/testfunctions/viridis.py
> Support for listed colormaps

- matplotlib2tikz/__init__.py
- matplotlib2tikz/axes.py
- test/test.py
- test/testfunctions/__init__.py
- test/testfunctions/colorbars.py
- test/testfunctions/subplots_with_colorbars.py
> Subplot colorbars

- matplotlib2tikz/axes.py
Bug fix for https://github.com/nschloe/matplotlib2tikz/issues/122
> Added support for minor ticks for normal axes and colorbars

- matplotlib2tikz/legend.py
- test/testfunctions/__init__.py
- test/testfunctions/legend_best_location.py
- test/testfunctions/legends2.py
- test/testfunctions/text_overlay.py
Hi,
Here is a first trial to implement the "best" legend location. If you are interested... Any improvements are most welcome.
> First implementation of best location for legends

- matplotlib2tikz/axes.py
- matplotlib2tikz/image.py
- test/test_image_plot.py
- test/test_line_collection.py
Fixed missing yLabel at colorbar
> missing yLabel at colorbar

- matplotlib2tikz/__about__.py
- matplotlib2tikz/legend.py
- test/test_legend_columns.py
> Legend columns

- matplotlib2tikz/legend.py
- matplotlib2tikz/save.py
- test/test_legend_best_location.py
- test/test_legend_columns.py
- test/test_legend_labels.py
- test/test_legends.py
- test/test_legends2.py
tidied up pull request for legend colors and legend positions even outside of plot.
The last pull request was confusing in the end as well as my git history, so I started a new one.
Hopefully it is more obvious and understandable now.
> Legend colors and position

- matplotlib2tikz/save.py
I tried to implement an option to disable the axis environment.
I hope the PR is ok  and is actually usefull for other people :)
> add option to turn the axis environment of

- matplotlib2tikz/path.py
- matplotlib2tikz/save.py
- test/test_contourf.py
- test/test_scatter.py
contourf creates path collection a bit differently from other plots. Added capability for contourf plots in existing code in path.py and clabel rendering for contour with additional test in save.py. I couldn't run the tests, since tests always fail for me even with original code. 
Solves #208.
> Added feature of contourf plot

- matplotlib2tikz/files.py
> Always use forward slash / in LaTeX relative paths

- matplotlib2tikz/line2d.py
- matplotlib2tikz/save.py
fix #271 by making "encoding" a visible parameter and mention it in docstring of the save function
> fix #271 by making "encoding" visible and mention it in docstring

- matplotlib2tikz/save.py
- test/test_fillstyle_reference.tex
> remove superfluous Spines

- matplotlib2tikz/axes.py
- matplotlib2tikz/line2d.py
- matplotlib2tikz/text.py
> remove superfluous print() statements

- README.md
- matplotlib2tikz/axes.py
- matplotlib2tikz/legend.py
- matplotlib2tikz/line2d.py
- matplotlib2tikz/save.py
- test/test_datetime.py
- test/test_datetime_reference.tex
> support for datetime

- README.md
- matplotlib2tikz/line2d.py
- matplotlib2tikz/text.py
- matplotlib2tikz/util.py
- test/test_axvline.py
- test/test_axvline_reference.tex
> reintroduce data transform

- tikzplotlib/axes.py
- tikzplotlib/line2d.py
> unicode fix for ticklabels for Python 2

- test/test_fancy_colorbar_reference.tex
- test/test_noise2_reference.tex
- test/test_noise_reference.tex
- test_requirements.txt
- tikzplotlib/axes.py
Fixed axis direction by conditionally adding options to the axis option array. Fixes two issues as specified in the commit message.
> Inverse axis fix

- .circleci/config.yml
- .github/workflows/test.yml
- test/refresh_reference_files.py
- test/test_line_set_data.py
- test/test_line_set_data_reference.tex
- tikzplotlib/line2d.py
> protect against int/float in xdata

- test/test_barchart_legend_reference.tex
- test/test_basic_sin_reference.tex
- test/test_histogram_reference.tex
- test/test_legend3_reference.tex
- test/test_legend_best_location.py
- test/test_legend_best_location_reference.tex
- test/test_legend_columns_reference.tex
- test/test_legend_labels_reference.tex
- test/test_legend_line_scatter_reference.tex
- test/test_legends2.py
- test/test_legends2_reference.tex
- test/test_legends_reference.tex
- test/test_steps_reference.tex
- test/test_text_overlay_reference.tex
- tikzplotlib/__about__.py
- tikzplotlib/_legend.py
> Legend opacity

- tikzplotlib/_axes.py
> fixing deprecated function call #353

- test/test_datetime_paths.py
- test/test_datetime_paths_reference.tex
- tikzplotlib/_path.py
> Support paths with datetime x-axis (nschloe#328)

- test/test_annotate_reference.tex
- test/test_arrows_reference.tex
- test/test_patches.py
- test/test_patches_reference.tex
- tikzplotlib/_patch.py
- tikzplotlib/_text.py
See the black arrows added to `test_patch`:
> Add support for FancyArrowPatch objects

- test/test_rotated_labels.py
- tikzplotlib/_axes.py
- tikzplotlib/_save.py
> rename figure{width,height} to axis_{width,height}

- README.md
- test/helpers.py
- test/test_annotate_reference.tex
- test/test_colorbars.py
- test/test_legend_line_scatter.py
- test/test_legend_line_scatter_reference.tex
- test/test_marker_reference.tex
- test/test_scatter_reference.tex
- tikzplotlib/_path.py
- tikzplotlib/_save.py
- tikzplotlib/_text.py
> Compile check

- tikzplotlib/_image.py
fix #422 by avoid multiplying uint8 image data with 255
> don't multiply by 255 is data is already uint8

- src/tikzplotlib/_line2d.py
> fix extern tables

- .github/workflows/ci.yml
- setup.cfg
- src/tikzplotlib/_files.py
- src/tikzplotlib/_image.py
- src/tikzplotlib/_quadmesh.py
- src/tikzplotlib/_save.py
- tests/test_viridis.py
> try windows tests

- src/tikzplotlib/_line2d.py
apparently, triple braces are here #535
> need triple braces for f-string
